# Dockerfile
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 5000

# Healthcheck встроенный в Dockerfile (опционально)
#HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
#  CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:5000')"

CMD ["python", "app.py"]